select      internal_uuid,
            nullif(trim(seeding_id),'')::int                    as seeding_id,
            nullif(lower(trim(platform)),'')                    as platform,
            nullif(lower(trim(handle)),'')                      as handle,
            nullif(lower(trim(initiation_direction)),'')        as initiation_direction,
            nullif(trim(first_contacted_date),'')::date         as first_contacted_date,
            nullif(trim(product_id_sent),'')                    as product_id_sent,
            nullif(lower(trim(product_type)),'')                as product_type,
            nullif(trim(delivered_date),'')::date               as delivered_date,
            nullif(trim(first_posted_date),'')::date            as first_posted_date,
            nullif(trim(num_static_posts),'')::smallint         as num_static_posts,
            nullif(trim(num_short_form_videos),'')::smallint    as num_short_form_videos,
            nullif(trim(num_ephemeral),'')::smallint            as num_ephemeral,
            nullif(trim(pinned_content),'')::boolean            as pinned_content,
            nullif(trim(post_effort_level),'')::smallint        as post_effort_level,
            nullif(trim(support_level),'')::smallint            as support_level,
            nullif(trim(posted_after_initial),'')::boolean      as posted_after_initial,
            nullif(trim(sent_raw_footage),'')::boolean          as sent_raw_footage,
            nullif(trim(notes),'')                              as notes,
            processed_at::timestamp
from        {{ source('google_sheets', 'creator_seedings') }}