select      internal_uuid,
            nullif(trim(order_id),'')::int                  as order_id,
            nullif(trim(ordered_timestamp),'')::timestamp   as ordered_timestamp,
            nullif(trim(customer_name),'')                  as customer_name,
            nullif(trim(purchase_id),'')                    as purchase_id,
            nullif(lower(trim(purchase_type)),'')           as purchase_type,
            nullif(trim(quantity),'')::smallint             as quantity,
            nullif(trim(paid_date),'')::date                as paid_date,
            nullif(lower(trim(payment_method)),'')          as payment_method,
            nullif(trim(price_at_purchase), '')::int        as price_at_purchase,
            nullif(lower(trim(price_adjustment_reason)),'') as price_adjustment_reason,
            nullif(lower(trim(platform)),'')                as platform,
            nullif(lower(trim(delivery_method)),'')         as delivery_method,
            nullif(trim(delivered_date),'')::date           as delivered_date,
            nullif(trim(delivery_fee),'')::int              as delivery_fee,
            nullif(trim(delivery_address),'')               as delivery_address,
            nullif(trim(cancelled_date),'')::date           as cancelled_date,
            nullif(trim(notes),'')                          as notes,
            processed_at::timestamp
from        {{ source('google_sheets', 'direct_sales') }}