select      internal_uuid,
            nullif(trim(order_id),'')::int                      as order_id,
            nullif(trim(supplier_paid_date),'')::date           as supplier_paid_date,
            nullif(trim(purchase_name),'')                      as purchase_name,
            nullif(lower(trim(purchase_type)),'')               as purchase_type,
            nullif(trim(order_quantity),'')::smallint           as order_quantity,
            nullif(lower(trim(order_unit)),'')                  as order_unit,
            nullif(trim(unit_net_weight_g),'')::smallint        as unit_net_weight_g,
            nullif(trim(original_order_total_cost),'')::float   as original_order_total_cost,
            nullif(upper(trim(original_order_currency)),'')     as original_order_currency,
            nullif(trim(converted_order_cost_php),'')::float    as converted_order_cost_php,
            nullif(trim(supplier_shipped_date),'')::date        as supplier_shipped_date,
            nullif(trim(supplier_name),'')                      as supplier_name,
            nullif(trim(supplier_contact),'')                   as supplier_contact,
            nullif(trim(rejects),'')::smallint                  as rejects,
            nullif(trim(notes),'')                              as notes,
            processed_at::timestamp
from        {{ source('google_sheets', 'supplier_order_line_items') }}