select      internal_uuid,
            nullif(order_id,'')::int                        as order_id,
            nullif(order_timestamp,'')::timestamp           as order_timestamp,
            nullif(trim(customer_name),'')                  as customer_name,
            nullif(upper(trim(sku_id)),'')                  as sku_id,
            nullif(quantity,'')::smallint                   as quantity,
            nullif(payment_date,'')::date                   as payment_date,
            nullif(lower(trim(payment_method)),'')          as payment_method,
            nullif(price_at_purchase, '')::int              as price_at_purchase,
            nullif(lower(trim(price_adjustment_reason)),'') as price_adjustment_reason,
            nullif(lower(trim(platform)),'')                as platform,
            nullif(lower(trim(delivery_method)),'')         as delivery_method,
            nullif(delivery_date,'')::date                  as delivery_date,
            nullif(delivery_fee,'')::int                    as delivery_fee,
            nullif(trim(delivery_address),'')               as delivery_address,
            nullif(cancel_date,'')::date                    as cancel_date,
            nullif(trim(notes),'')                          as notes,
            processed_at::timestamp
from        {{ source('google_sheets', 'direct_sales') }}