
name: 'bark_warehouse'
version: '1.7.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'bark_warehouse'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Global config for all models in folder. Can be overridden in the
# individual model files using the `{{ config(...) }}` macro.
models:
  bark_warehouse:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table

seeds:
  bark_warehouse:
    google_sheets:
      +schema: ci_seed