bark_warehouse:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: public
    ci:
      type: postgres
      host: localhost
      user: testuser
      password: testpass
      port: 5432
      dbname: testdb
      schema: public
      threads: 4
  target: dev